#!/bin/bash
DOTVIM=`pwd`

mkdir -p "$HOME/.vim"
mkdir -p "$HOME/.vim/undo"
ln -fs "$DOTVIM/config/.vimrc" "$HOME/.vimrc"

mkdir -p "$HOME/.vim/UltiSnips"
for file in $DOTVIM/snippets/*.snippets; do
	ln -fs "$file" "$HOME/.vim/UltiSnips/$(basename $file)"
done

if [ ! -d "$HOME/.vim/bundle" ]; then
	ln -fs "$DOTVIM/plugins" "$HOME/.vim/bundle"
fi
