#!/bin/bash
DOTVIM=`pwd`

ln -fs "$DOTVIM/config/init.vim" "$HOME/.config/nvim/init.vim"
mkdir -p "$HOME/.config/nvim/lua/"
ln -fs "$DOTVIM/config/plugins.lua" "$HOME/.config/nvim/lua/plugins.lua"
ln -fs "$DOTVIM/config/alpha-nvim.lua" "$HOME/.config/nvim/lua/alpha-nvim.lua"
touch "$HOME/.config/nvim/local.vim"
